# Create SSL Certbot (Cerbot needs use 80 port to test domain)
- name: run certbot
  command: certbot certonly --email devops@talentosoftware.com  --apache -n  -d {{ hostname }}  --agree-tos 
  become: yes

# Create folder 
- name: Create project folder /var/www/html/{{ hostname }}
  file:
    path: /var/www/html/{{ hostname }}
    state: directory
  become: yes

# Create virtualhost
- name: Install VirtualHost file 
  template:
    src: templates/VirtualHost.j2
    dest: /etc/httpd/sites-available/{{ hostname }}.conf
  become: yes

# Enable site
- name: Enable VirtualHost
  file:
    src: /etc/httpd/sites-available/{{ hostname }}.conf
    dest: /etc/httpd/sites-enabled/{{ hostname }}.conf
    state: link
  become: yes

# Reload httpd
- name: Enable reload httpd on systemctl
  systemd:
    name: httpd
    state: restarted
    enabled: yes
  become: yes
