- name: Install epel repository 
  yum:
    name: epel-release
    state: latest
  become: yes

- name: Install apache 
  yum:
    name: httpd
    state: latest
  become: yes

- name: Add nodejs repo 6x
  shell: curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
  become: yes
  
- name: Install nodejs
  yum:
    name: nodejs
    state: latest
  become: yes

- name: Install vim
  yum:
    name: vim
    state: latest
  become: yes

- name: Install Certbot (mod_ssl)
  yum: 
    name: mod_ssl
    state: latest
  become: yes

- name: Install Certbot (python-certbot-apache)
  yum:
    name: python-certbot-apache
    state: latest
  become: yes
